apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-app
  labels:
    app: simple-nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-nodejs-app
  template:
    metadata:
      labels:
        app: simple-nodejs-app
    spec:
      containers:
      - name: simple-nodejs-app
        image: your-dockerhub-username/simple-nodejs-app:latest
        ports:
        - containerPort: 3000
